export const ErrorMessages = {
    FIELDS_REQUIERED: "Fields are required to create a product",
    PRODUCT_NOT_FOUND: "Product not found",
    PRODUCTS_NOT_FOUND: "Products not found",
    DELETE_PRODUCT_ERROR: "Credential is not sufficient to delete product",
    ADD_PRODUCT_TO_CART_ERROR: "You cannot add a product that you have already added to the cart.",
    PRODUCT_NOT_FOUND_IN_CART: "Product not found in cart",
    CART_NOT_FOUND: "Cart not found",
    CARTS_NOT_FOUND: "Carts not found",
    USER_NOT_FOUND: "User not found",
    USERS_NOT_FOUND: "Users not found",
    TICKET_NOT_FOUND: "Ticket not found",
    TICKETS_NOT_FOUND: "Tickets not found",
    RESET_PASSWORD_ERROR: "Password is the same as before",
    SESSION_NOT_FOUND: "Session not found",
    DOCUMENTS_VERIFICATION_IDENTITY: "Documents are required to verify identity",
}